---
title: "Homework Four"
output: html_document
---

# Homework Four: Due Sept. 28  at 5 pm.

First, download your homework. In your RStudio, fill in the below command:

```{r, eval = FALSE}
download.file(url = "https://raw.githubusercontent.com/BiologicalDataAnalysis2019/2022/main/vignettes/homework_4.Rmd", destfile = "")

```

# Question One:

Take a look at [this](https://github.com/ropensci/treedata.table) package. Reading the documentation, what is the primary goal of this package? 

```
#Answer Here
```

# Question Two

Where in this package is the actual code stored? How do you know?

```
# Answer here

```

# Question 3

When you look into the code, are you able to understand any of it? What is one thing the authors could do to make the code more understandable?

```
# Answer here
```

# Question 4

What are the other directories in the package? What do they contain?

```
Answer here

```

# Question 5

Do you trust that this package does what it says it is doing? Why or why not? 

```
Answer here
```

# Question 6

Have a look at [these](https://libguides.bc.edu/dataplan/best_practices) data storage best practices from Boston College. Have this read by Sept. 27 as we will use this in an activity.

## Master's Students

Find a package that does something you'd like to do for your dissertation. Apply the steps above to this package to evaluate its reliability.
