---
title: "notes08-29-24"
author: "Noah Irwin"
date: "2024-08-29"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Notes for class on Thursday 8/29
factors are like (male female or undefined)
Tidyverse cant handle factors
select(surveys,plot_id, species_id,weight)
# A tibble: 34,786 × 3
   plot_id species_id weight
     <dbl> <chr>       <dbl>
 1       2 NL             NA
 2       2 NL             NA
 3       2 NL             NA
 4       2 NL             NA
 5       2 NL             NA
 6       2 NL             NA
 7       2 NL             NA
 8       2 NL             NA
 9       2 NL            218
10       2 NL             NA
# ℹ 34,776 more rows
# ℹ Use `print(n = ...)` to see more rows
> ## excluditaory select
 select(surveys,-record_id,-species_id)
# A tibble: 34,786 × 11
   month   day  year plot_id sex   hindfoot_length weight genus species
   <dbl> <dbl> <dbl>   <dbl> <chr>           <dbl>  <dbl> <chr> <chr>  
 1     7    16  1977       2 M                  32     NA Neot… albigu…
 2     8    19  1977       2 M                  31     NA Neot… albigu…
 3     9    13  1977       2 NA                 NA     NA Neot… albigu…
 4    10    16  1977       2 NA                 NA     NA Neot… albigu…
 5    11    12  1977       2 NA                 NA     NA Neot… albigu…
 6    11    12  1977       2 NA                 NA     NA Neot… albigu…
 7    12    10  1977       2 NA                 NA     NA Neot… albigu…
 8     1     8  1978       2 NA                 NA     NA Neot… albigu…
 9     2    18  1978       2 M                  NA    218 Neot… albigu…
10     3    11  1978       2 NA                 NA     NA Neot… albigu…
# ℹ 34,776 more rows
# ℹ 2 more variables: taxa <chr>, plot_type <chr>
# ℹ Use `print(n = ...)` to see more rows
> ## Filter
shows only the data for the year 1995
filter(surveys,year==1995)
# A tibble: 1,180 × 13
   record_id month   day  year plot_id species_id sex   hindfoot_length
       <dbl> <dbl> <dbl> <dbl>   <dbl> <chr>      <chr>           <dbl>
 1     22314     6     7  1995       2 NL         M                  34
 2     22728     9    23  1995       2 NL         F                  32
 3     22899    10    28  1995       2 NL         F                  32
 4     23032    12     2  1995       2 NL         F                  33
 5     22003     1    11  1995       2 DM         M                  37
 6     22042     2     4  1995       2 DM         F                  36
 7     22044     2     4  1995       2 DM         M                  37
 8     22105     3     4  1995       2 DM         F                  37
 9     22109     3     4  1995       2 DM         M                  37
10     22168     4     1  1995       2 DM         M                  36
# ℹ 1,170 more rows
# ℹ 5 more variables: weight <dbl>, genus <chr>, species <chr>,
#   taxa <chr>, plot_type <chr>
# ℹ Use `print(n = ...)` to see more rows

##Exculsion Opperator Excludes all data from the 1995 and presents the rest
filter(surveys,year!=1995)
# A tibble: 33,606 × 13
   record_id month   day  year plot_id species_id sex   hindfoot_length
       <dbl> <dbl> <dbl> <dbl>   <dbl> <chr>      <chr>           <dbl>
 1         1     7    16  1977       2 NL         M                  32
 2        72     8    19  1977       2 NL         M                  31
 3       224     9    13  1977       2 NL         NA                 NA
 4       266    10    16  1977       2 NL         NA                 NA
 5       349    11    12  1977       2 NL         NA                 NA
 6       363    11    12  1977       2 NL         NA                 NA
 7       435    12    10  1977       2 NL         NA                 NA
 8       506     1     8  1978       2 NL         NA                 NA
 9       588     2    18  1978       2 NL         M                  NA
10       661     3    11  1978       2 NL         NA                 NA
# ℹ 33,596 more rows
# ℹ 5 more variables: weight <dbl>, genus <chr>, species <chr>,
#   taxa <chr>, plot_type <chr>
# ℹ Use `print(n = ...)` to see more rows

surveys_small <- filter(surveys, weight <5)
> surveys_small
# A tibble: 17 × 13
   record_id month   day  year plot_id species_id sex   hindfoot_length
       <dbl> <dbl> <dbl> <dbl>   <dbl> <chr>      <chr>           <dbl>
 1      4052     4     5  1981       3 PF         F                  15
 2      7084    11    22  1982       3 PF         F                  16
 3     28126     6    28  1998      15 PF         M                  NA
 4      9909     1    20  1985      15 RM         F                  15
 5      9853     1    19  1985      17 RM         M                  16
 6      4290     4     6  1981       4 PF         NA                 NA
 7     29906    10    10  1999       4 PP         M                  21
 8      8736    12     8  1983      19 RM         M                  17
 9      9799     1    19  1985      19 RM         M                  16
10      9794     1    19  1985      24 RM         M                  16
11       218     9    13  1977       1 PF         M                  13
12      5346     2    22  1982      21 PF         F                  14
13      9937     2    16  1985      21 RM         M                  16
14     10119     3    17  1985      10 RM         M                  16
15      9790     1    19  1985      16 RM         F                  16
16      9823     1    19  1985      23 RM         M                  16
17     10439     5    24  1985       7 RM         M                  16
# ℹ 5 more variables: weight <dbl>, genus <chr>, species <chr>,
#   taxa <chr>, plot_type <chr>
> surveys_even_smaller<-select (surveys_small, species_id,sex,weight)
> surveys_even_smaller
# A tibble: 17 × 3
   species_id sex   weight
   <chr>      <chr>  <dbl>
 1 PF         F          4
 2 PF         F          4
 3 PF         M          4
 4 RM         F          4
 5 RM         M          4
 6 PF         NA         4
 7 PP         M          4
 8 RM         M          4
 9 RM         M          4
10 RM         M          4
11 PF         M          4
12 PF         F          4
13 RM         M          4
14 RM         M          4
15 RM         F          4
16 RM         M          4
17 RM         M          4
> ### Condesnesd into a single function
surveys_small<-select(filter(surveys,weight<5),species_id,weight,sex)


##using %>% 
we pipe our data through differnt stages of filtration
surveys %>% 
+ filter(weight<5) %>% 
+ select(species_id,sex,weight)
# A tibble: 17 × 3
   species_id sex   weight
   <chr>      <chr>  <dbl>
 1 PF         F          4
 2 PF         F          4
 3 PF         M          4
 4 RM         F          4
 5 RM         M          4
 6 PF         NA         4
 7 PP         M          4
 8 RM         M          4
 9 RM         M          4
10 RM         M          4
11 PF         M          4
12 PF         F          4
13 RM         M          4
14 RM         M          4
15 RM         F          4
16 RM         M          4
17 RM         M          4
> #saving a pipe tot he global environment
surveys_sml<-surveys %>% 
+ filter(weight<5) %>% 
+ select(species_id,sex,weight)
> 
> surveys_sml
# A tibble: 17 × 3
   species_id sex   weight
   <chr>      <chr>  <dbl>
 1 PF         F          4
 2 PF         F          4
 3 PF         M          4
 4 RM         F          4
 5 RM         M          4
 6 PF         NA         4
 7 PP         M          4
 8 RM         M          4
 9 RM         M          4
10 RM         M          4
11 PF         M          4
12 PF         F          4
13 RM         M          4
14 RM         M          4
15 RM         F          4
16 RM         M          4
17 RM         M          4
> ## Filter data from the year prior to 1995 (<)
surveys %>% 
+ filter(year<=1995) %>% 
+ select(sex,weight,year)
# A tibble: 22,666 × 3
   sex   weight  year
   <chr>  <dbl> <dbl>
 1 M         NA  1977
 2 M         NA  1977
 3 NA        NA  1977
 4 NA        NA  1977
 5 NA        NA  1977
 6 NA        NA  1977
 7 NA        NA  1977
 8 NA        NA  1978
 9 M        218  1978
10 NA        NA  1978
# ℹ 22,656 more rows
# ℹ Use `print(n = ...)` to see more row

##To check you can ask it to summarize to check
summary(nineteenninteyfive)
     sex                weight            year     
 Length:22666       Min.   :  4.00   Min.   :1977  
 Class :character   1st Qu.: 21.00   1st Qu.:1982  
 Mode  :character   Median : 40.00   Median :1986  
                    Mean   : 47.76   Mean   :1986  
                    3rd Qu.: 50.00   3rd Qu.:1990  
                    Max.   :278.00   Max.   :1995  
                    NA's   :1859                 
##Shows max of 1995 so you must change your %>% filter
nineteenninteyfive<-surveys %>% 
+ filter(year<1995) %>% 
+ select(sex,weight,year)
> 
> nineteenninteyfive
# A tibble: 21,486 × 3
   sex   weight  year
   <chr>  <dbl> <dbl>
 1 M         NA  1977
 2 M         NA  1977
 3 NA        NA  1977
 4 NA        NA  1977
 5 NA        NA  1977
 6 NA        NA  1977
 7 NA        NA  1977
 8 NA        NA  1978
 9 M        218  1978
10 NA        NA  1978
# ℹ 21,476 more rows
# ℹ Use `print(n = ...)` to see more rows
> summary(nineteenninteyfive)
     sex                weight            year     
 Length:21486       Min.   :  4.00   Min.   :1977  
 Class :character   1st Qu.: 22.00   1st Qu.:1982  
 Mode  :character   Median : 41.00   Median :1985  
                    Mean   : 48.76   Mean   :1985  
                    3rd Qu.: 50.00   3rd Qu.:1989  
                    Max.   :278.00   Max.   :1994  
                    NA's   :1765          
                    
### Mutate your Data
surveys %>% 
+ mutate(weight_kg=weight/1000) %>% 
+ select(year,species_id,weight_kg)
# A tibble: 34,786 × 3
    year species_id weight_kg
   <dbl> <chr>          <dbl>
 1  1977 NL            NA    
 2  1977 NL            NA    
 3  1977 NL            NA    
 4  1977 NL            NA    
 5  1977 NL            NA    
 6  1977 NL            NA    
 7  1977 NL            NA    
 8  1978 NL            NA    
 9  1978 NL             0.218
10  1978 NL            NA    
# ℹ 34,776 more rows
# ℹ Use `print(n = ...)` to see more rows
> ##More
surveys %>% 
+ mutate(weight_kg=weight/1000,
+        weight_kg2=weight_kg*2) %>% 
+ select(weight_kg2,species_id,weight_kg)
# A tibble: 34,786 × 3
   weight_kg2 species_id weight_kg
        <dbl> <chr>          <dbl>
 1     NA     NL            NA    
 2     NA     NL            NA    
 3     NA     NL            NA    
 4     NA     NL            NA    
 5     NA     NL            NA    
 6     NA     NL            NA    
 7     NA     NL            NA    
 8     NA     NL            NA    
 9      0.436 NL             0.218
10     NA     NL            NA    
# ℹ 34,776 more rows
# ℹ Use `print(n = ...)` to see more rows
###Missing Data removing Na's
surveys %>% 
+ filter(!is.na(weight)) %>% 
+ mutate(weight_kg=weight/1000) %>% 
+ select(year,species_id,weight,weight_kg)
# A tibble: 32,283 × 4
    year species_id weight weight_kg
   <dbl> <chr>       <dbl>     <dbl>
 1  1978 NL            218     0.218
 2  1978 NL            204     0.204
 3  1978 NL            200     0.2  
 4  1978 NL            199     0.199
 5  1978 NL            197     0.197
 6  1978 NL            218     0.218
 7  1979 NL            166     0.166
 8  1979 NL            184     0.184
 9  1979 NL            206     0.206
10  1979 NL            274     0.274
# ℹ 32,273 more rows
# ℹ Use `print(n = ...)` to see more rows

##In class assignment
assigment<-surveys %>%
+ filter(!is.na(hindfoot_length)) %>%
+ mutate(femur_length=hindfoot_length/2) %>%
+ filter(femur_length>30) %>%
+ select(species_id,femur_length)
> 
> assigment
# A tibble: 2 × 2
  species_id femur_length
  <chr>             <dbl>
1 NL                   35
2 DO                   32
> 
##Split Apply Combine 
summarise is differnet then mutate as it prsents only the data that you summarised
surveys %>% 
+ group_by(sex) %>% 
+ summarise(mean_weight=mean(weight,na.rm = TRUE))
# A tibble: 3 × 2
  sex   mean_weight
  <chr>       <dbl>
1 F            42.2
2 M            43.0
3 NA           64.7
> 
##or
surveys %>% 
+ filter(!is.na(weight)) %>% 
+ group_by(sex) %>% 
+ summarise(mean_weight=mean(weight))
# A tibble: 3 × 2
  sex   mean_weight
  <chr>       <dbl>
1 F            42.2
2 M            43.0
3 NA           64.7
> 
###More Spliting
surveys %>% 
+ filter(!is.na(weight)) %>% 
+ group_by(sex,species_id) %>% 
+ summarise(mean_weight=mean(weight))
`summarise()` has grouped output by 'sex'. You can override using the
`.groups` argument.
# A tibble: 64 × 3
# Groups:   sex [3]
   sex   species_id mean_weight
   <chr> <chr>            <dbl>
 1 F     BA                9.16
 2 F     DM               41.6 
 3 F     DO               48.5 
 4 F     DS              118.  
 5 F     NL              154.  
 6 F     OL               31.1 
 7 F     OT               24.8 
 8 F     OX               21   
 9 F     PB               30.2 
10 F     PE               22.8 
# ℹ 54 more rows
# ℹ Use `print(n = ...)` to see more rows